name: Update packages

on:
  # schedule:
  #   - cron:  '0 6 * * *'
  workflow_dispatch:

jobs:
  update:
    runs-on: windows-latest
    name: Update dependencies
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          ref: develop

      - name: Setup Current .NET SDK
        uses: actions/setup-dotnet@v2.0.0

      - name: Setup Tools .NET SDK
        uses: actions/setup-dotnet@v2.0.0
        with:
          dotnet-version: '3.1.x'

      - name: Run Nukeeper
        shell: pwsh
        env:
          NUKEEPER_TOKEN: ${{secrets.NUKEEPER_TOKEN}}
        run: |
          ./build.ps1 UpdateNuGetPackages --is-ci --nukeeper-token $env:NUKEEPER_TOKEN
