name: Publish

on:
  push:
    branches:
      - master

jobs:
  Publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Restore
        shell: pwsh
        run: |
          dotnet restore

      - name: Build
        shell: pwsh
        run: |
          MSBuild /property:Configuration=Release

      - name: Publish Nuget
        shell: pwsh
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        run: |
          Get-ChildItem -Filter *.nupkg -Recurse -ErrorAction SilentlyContinue -Force | % { nuget push $_.FullName $env:NUGET_API_KEY -Source https://api.nuget.org/v3/index.json }
