name: Publish

on:
  push:
    branches:
      - master

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Publish Injecter to nuget.org
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: Injecter/Injecter.csproj
          TAG_COMMIT: "false"
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key

      - name: Publish Injecter.Avalonia to nuget.org
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: Injecter.Avalonia/Injecter.Avalonia.csproj
          TAG_COMMIT: "false"
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key

      - name: Publish Injecter.Wpf to nuget.org
        uses: rohith/publish-nuget@v2
        continue-on-error: true
        with:
          PROJECT_FILE_PATH: Injecter.Wpf/Injecter.Wpf.csproj
          TAG_COMMIT: "false"
          NUGET_KEY: ${{secrets.NUGET_API_KEY}} # nuget.org API key
      
