name: Publish To GitHub Pages

on:
  push:
    branches:
      - "master"

jobs:
  Deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1

      - name: Build DocFX
        shell: pwsh
        run: ./build.ps1 BuildDocs --is-ci

      - name: Deploy to GitHub Pages
        uses: crazy-max/ghaction-github-pages@v2.6.0
        with:
          target_branch: gh-pages
          build_dir: Documentation/_site
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}      
