name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  Publish:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Publish
        env:
          NUGET_API_KEY: ${{ secrets.NUGET_API_KEY }}
        shell: pwsh
        run: ./build.ps1 PublishNuGetPackages --nuget-api-key $env:NUGET_API_KEY --configuration Release
