name: Run Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:
  workflow_dispatch:

jobs:
  RunTests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.0
        with:
          fetch-depth: 0

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v2.0.0

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.1.1

      - name: Set up JDK
        uses: actions/setup-java@v3.0.0
        with:
          java-version: 17

      - name: Test
        shell: pwsh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          SONAR_TOKEN: ${{secrets.SONAR_TOKEN}}
        run: |
          ./build.ps1 RunSonar `
          --is-ci `
          --configuration Release `
          --sonar-host-url "https://sonarcloud.io" `
          --sonar-project-key "KuraiAndras_Injecter" `
          --sonar-token "${{ secrets.SONAR_TOKEN }}" `
          --sonar-organization "kuraiandras"
