name: Run Tests

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  TestSonar:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Remove hard projects
        run : |
          dotnet sln Injecter.sln remove Injecter.Uwp/Injecter.Uwp.csproj
          dotnet sln Injecter.sln remove Injecter.UwpExample/Injecter.UwpExample.csproj
          dotnet sln Injecter.sln remove Injecter.Wpf/Injecter.Wpf.csproj
          dotnet sln Injecter.sln remove Injecter.Hosting.Wpf/Injecter.Hosting.Wpf.csproj
          dotnet sln Injecter.sln remove Injecter.Unity.Dependencies/Injecter.Unity.Dependencies.csproj  

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release /WarnAsError

      - name: Test
        run: dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover
