name: Run Tests

on:
  pull_request:

jobs:
  RunTests:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.0.2

      - name: Test
        shell: pwsh
        run: ./build.ps1 Test --configuration Release
