name: Tests, Sonar

on:
  push:
    branches:
      - master
      - develop
  pull_request:

jobs:
  TestSonar:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v2

      - name: Fetch unshallow
        run: |
          git fetch --unshallow

      - name: Setup .NET Core SDK
        uses: actions/setup-dotnet@v1.7.2

      - name: Install Sonar Scanner
        run: |
          dotnet tool install dotnet-sonarscanner -g

      - name: Sonar Begin
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner begin /k:"KuraiAndras_Injecter" /o:"kuraiandras" /d:sonar.login="${{ secrets.SONAR_TOKEN }}" /d:sonar.host.url="https://sonarcloud.io" /d:sonar.cs.opencover.reportsPaths="**/coverage.opencover.xml"

      - name: Remove hard projects
        run : |
          dotnet sln Injecter.sln remove Injecter.Uwp/Injecter.Uwp.csproj
          dotnet sln Injecter.sln remove Injecter.UwpExample/Injecter.UwpExample.csproj
          dotnet sln Injecter.sln remove Injecter.Wpf/Injecter.Wpf.csproj
          dotnet sln Injecter.sln remove Injecter.Hosting.Wpf/Injecter.Hosting.Wpf.csproj
          dotnet sln Injecter.sln remove Injecter.Unity.Dependencies/Injecter.Unity.Dependencies.csproj  

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release /p:CollectCoverage=true /p:CoverletOutputFormat=opencover

      - name: End Sonar
        shell: powershell
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: |
          dotnet sonarscanner end /d:sonar.login="${{ secrets.SONAR_TOKEN }}"
